mysql:
  host: "us9.avocado.urubuhost.com"
  port: 3306
  database: "s1603_empire"
  username: "u1603_94Klgle0BM"
  password: "FadxP9=^gw92^9f5hRR^LG6g"

# IGNORE
CurrencyFormat:
  - ""
  - "k"
  - "M"
  - "B"
  - "T"
  - "Q"
  - "QQ"
  - "S"
  - "SS"
  - "OC"
  - "N"
  - "D"
  - "UN"
  - "DD"
  - "TR"
  - "QT"
  - "QN"
  - "SD"
  - "SPD"
  - "OD"
  - "ND"
  - "VG"
  - "UVG"
  - "DVG"
  - "TVG"
  - "QTV"
  - "QNV"
  - "SEV"
  - "SPV"
  - "OVG"
  - "NVG"
  - "TG"